---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Automatically creates the namespace before deploying resources
namespace: sample-app

resources:
  - namespace.yaml
  - configmap-secrets.yaml
  - db-deployment.yaml
  - backend-deployment.yaml
# Pro Tip: Kustomize can generate unique hashes for configmaps to trigger automatic deployment rollouts
